// Ciudades (municipios) y departamentos de Paraguay como predeterminado de la
// librería: 263 distritos oficiales con su departamento. El autocompletado
// resuelve el departamento solo con la ciudad (es dependiente de ella).
//
// El catálogo es bilingüe: cada fila trae `{ ciudad, departamento }` (español)
// y `{ city, department }` (inglés, el contrato de `CityAutocomplete` y del
// `buscar` propio de cada app). Las dos parejas apuntan al mismo dato; la
// fuente se mantiene en español y la exportada deriva las claves en inglés.
//
// Se actualiza acá y llega a todas las apps con el release de la librería.
// Fuente: lista oficial de municipios (misma que el backend de MobOS).

const MUNICIPIOS = [
  { ciudad: "Bahía Negra", departamento: "Alto Paraguay" },
  { ciudad: "Capitán Carmelo Peralta", departamento: "Alto Paraguay" },
  { ciudad: "Fuerte Olimpo", departamento: "Alto Paraguay" },
  { ciudad: "Puerto Casado", departamento: "Alto Paraguay" },
  { ciudad: "Ciudad del Este", departamento: "Alto Paraná" },
  { ciudad: "Doctor Juan León Mallorquín", departamento: "Alto Paraná" },
  { ciudad: "Doctor Raúl Peña", departamento: "Alto Paraná" },
  { ciudad: "Domingo Martínez de Irala", departamento: "Alto Paraná" },
  { ciudad: "Hernandarias", departamento: "Alto Paraná" },
  { ciudad: "Iruña", departamento: "Alto Paraná" },
  { ciudad: "Itakyry", departamento: "Alto Paraná" },
  { ciudad: "Juan Emiliano O''Leary", departamento: "Alto Paraná" },
  { ciudad: "Los Cedrales", departamento: "Alto Paraná" },
  { ciudad: "Mbaracayú", departamento: "Alto Paraná" },
  { ciudad: "Minga Guazú", departamento: "Alto Paraná" },
  { ciudad: "Minga Porá", departamento: "Alto Paraná" },
  { ciudad: "Naranjal", departamento: "Alto Paraná" },
  { ciudad: "Ñacunday", departamento: "Alto Paraná" },
  { ciudad: "Presidente Franco", departamento: "Alto Paraná" },
  { ciudad: "San Alberto", departamento: "Alto Paraná" },
  { ciudad: "San Cristóbal", departamento: "Alto Paraná" },
  { ciudad: "Santa Fe del Paraná", departamento: "Alto Paraná" },
  { ciudad: "Santa Rita", departamento: "Alto Paraná" },
  { ciudad: "Santa Rosa del Monday", departamento: "Alto Paraná" },
  { ciudad: "Tavapy", departamento: "Alto Paraná" },
  { ciudad: "Yguazú", departamento: "Alto Paraná" },
  { ciudad: "Bella Vista Norte", departamento: "Amambay" },
  { ciudad: "Capitán Bado", departamento: "Amambay" },
  { ciudad: "Cerro Corá", departamento: "Amambay" },
  { ciudad: "Karapaí", departamento: "Amambay" },
  { ciudad: "Pedro Juan Caballero", departamento: "Amambay" },
  { ciudad: "Zanja Pytá", departamento: "Amambay" },
  { ciudad: "Asunción", departamento: "Asunción" },
  { ciudad: "Boquerón", departamento: "Boquerón" },
  { ciudad: "Filadelfia", departamento: "Boquerón" },
  { ciudad: "Loma Plata", departamento: "Boquerón" },
  { ciudad: "Mariscal José Félix Estigarribia", departamento: "Boquerón" },
  { ciudad: "Caaguazú", departamento: "Caaguazú" },
  { ciudad: "Carayaó", departamento: "Caaguazú" },
  { ciudad: "Coronel Oviedo", departamento: "Caaguazú" },
  { ciudad: "Doctor Cecilio Báez", departamento: "Caaguazú" },
  { ciudad: "Doctor Juan Eulogio Estigarribia", departamento: "Caaguazú" },
  { ciudad: "Doctor Juan Manuel Frutos", departamento: "Caaguazú" },
  { ciudad: "José Domingo Ocampos", departamento: "Caaguazú" },
  { ciudad: "La Pastora", departamento: "Caaguazú" },
  { ciudad: "Mariscal Francisco Solano López", departamento: "Caaguazú" },
  { ciudad: "Nueva Londres", departamento: "Caaguazú" },
  { ciudad: "Nueva Toledo", departamento: "Caaguazú" },
  { ciudad: "Raúl Arsenio Oviedo", departamento: "Caaguazú" },
  { ciudad: "Regimiento de Infantería Tres Corrales", departamento: "Caaguazú" },
  { ciudad: "Repatriación", departamento: "Caaguazú" },
  { ciudad: "San Joaquín", departamento: "Caaguazú" },
  { ciudad: "San José de los Arroyos", departamento: "Caaguazú" },
  { ciudad: "Santa Rosa del Mbutuy", departamento: "Caaguazú" },
  { ciudad: "Simón Bolívar", departamento: "Caaguazú" },
  { ciudad: "Tembiaporá", departamento: "Caaguazú" },
  { ciudad: "Tres de Febrero", departamento: "Caaguazú" },
  { ciudad: "Vaquería", departamento: "Caaguazú" },
  { ciudad: "Yhú", departamento: "Caaguazú" },
  { ciudad: "Abaí", departamento: "Caazapá" },
  { ciudad: "Buena Vista", departamento: "Caazapá" },
  { ciudad: "Caazapá", departamento: "Caazapá" },
  { ciudad: "Doctor Moisés Santiago Bertoni", departamento: "Caazapá" },
  { ciudad: "Fulgencio Yegros", departamento: "Caazapá" },
  { ciudad: "General Higinio Morínigo", departamento: "Caazapá" },
  { ciudad: "Maciel", departamento: "Caazapá" },
  { ciudad: "San Juan Nepomuceno", departamento: "Caazapá" },
  { ciudad: "Tavaí", departamento: "Caazapá" },
  { ciudad: "Tres de Mayo", departamento: "Caazapá" },
  { ciudad: "Yuty", departamento: "Caazapá" },
  { ciudad: "Corpus Christi", departamento: "Canindeyú" },
  { ciudad: "Curuguaty", departamento: "Canindeyú" },
  { ciudad: "General Francisco Caballero Álvarez", departamento: "Canindeyú" },
  { ciudad: "Itanará", departamento: "Canindeyú" },
  { ciudad: "Katueté", departamento: "Canindeyú" },
  { ciudad: "La Paloma del Espíritu Santo", departamento: "Canindeyú" },
  { ciudad: "Laurel", departamento: "Canindeyú" },
  { ciudad: "Maracaná", departamento: "Canindeyú" },
  { ciudad: "Nueva Esperanza", departamento: "Canindeyú" },
  { ciudad: "Puerto Adela", departamento: "Canindeyú" },
  { ciudad: "Saltos del Guairá", departamento: "Canindeyú" },
  { ciudad: "Villa Ygatimí", departamento: "Canindeyú" },
  { ciudad: "Yasy Cañy", departamento: "Canindeyú" },
  { ciudad: "Yby Pytá", departamento: "Canindeyú" },
  { ciudad: "Ybyrarobaná", departamento: "Canindeyú" },
  { ciudad: "Ypejhú", departamento: "Canindeyú" },
  { ciudad: "Areguá", departamento: "Central" },
  { ciudad: "Capiatá", departamento: "Central" },
  { ciudad: "Fernando de la Mora", departamento: "Central" },
  { ciudad: "Guarambaré", departamento: "Central" },
  { ciudad: "Itá", departamento: "Central" },
  { ciudad: "Itauguá", departamento: "Central" },
  { ciudad: "Julián Augusto Saldívar", departamento: "Central" },
  { ciudad: "Lambaré", departamento: "Central" },
  { ciudad: "Limpio", departamento: "Central" },
  { ciudad: "Luque", departamento: "Central" },
  { ciudad: "Mariano Roque Alonso", departamento: "Central" },
  { ciudad: "Nueva Italia", departamento: "Central" },
  { ciudad: "Ñemby", departamento: "Central" },
  { ciudad: "San Antonio", departamento: "Central" },
  { ciudad: "San Lorenzo", departamento: "Central" },
  { ciudad: "Villa Elisa", departamento: "Central" },
  { ciudad: "Villeta", departamento: "Central" },
  { ciudad: "Ypacaraí", departamento: "Central" },
  { ciudad: "Ypané", departamento: "Central" },
  { ciudad: "Arroyito", departamento: "Concepción" },
  { ciudad: "Azotey", departamento: "Concepción" },
  { ciudad: "Belén", departamento: "Concepción" },
  { ciudad: "Concepción", departamento: "Concepción" },
  { ciudad: "Horqueta", departamento: "Concepción" },
  { ciudad: "Itacuá", departamento: "Concepción" },
  { ciudad: "Loreto", departamento: "Concepción" },
  { ciudad: "Paso Barreto", departamento: "Concepción" },
  { ciudad: "Paso Horqueta", departamento: "Concepción" },
  { ciudad: "San Alfredo", departamento: "Concepción" },
  { ciudad: "San Carlos del Apa", departamento: "Concepción" },
  { ciudad: "San Lázaro", departamento: "Concepción" },
  { ciudad: "Sargento José Félix López", departamento: "Concepción" },
  { ciudad: "Yby Yaú", departamento: "Concepción" },
  { ciudad: "Altos", departamento: "Cordillera" },
  { ciudad: "Arroyos y Esteros", departamento: "Cordillera" },
  { ciudad: "Atyrá", departamento: "Cordillera" },
  { ciudad: "Caacupé", departamento: "Cordillera" },
  { ciudad: "Caraguatay", departamento: "Cordillera" },
  { ciudad: "Emboscada", departamento: "Cordillera" },
  { ciudad: "Eusebio Ayala", departamento: "Cordillera" },
  { ciudad: "Isla Pucú", departamento: "Cordillera" },
  { ciudad: "Itacurubí de la Cordillera", departamento: "Cordillera" },
  { ciudad: "Juan de Mena", departamento: "Cordillera" },
  { ciudad: "Loma Grande", departamento: "Cordillera" },
  { ciudad: "Mbocayaty del Yhaguy", departamento: "Cordillera" },
  { ciudad: "Nueva Colombia", departamento: "Cordillera" },
  { ciudad: "Piribebuy", departamento: "Cordillera" },
  { ciudad: "Primero de Marzo", departamento: "Cordillera" },
  { ciudad: "San Bernardino", departamento: "Cordillera" },
  { ciudad: "San José Obrero", departamento: "Cordillera" },
  { ciudad: "Santa Elena", departamento: "Cordillera" },
  { ciudad: "Tobatí", departamento: "Cordillera" },
  { ciudad: "Valenzuela", departamento: "Cordillera" },
  { ciudad: "Borja", departamento: "Guairá" },
  { ciudad: "Capitán Mauricio José Troche", departamento: "Guairá" },
  { ciudad: "Coronel Martínez", departamento: "Guairá" },
  { ciudad: "Doctor Botrell", departamento: "Guairá" },
  { ciudad: "Félix Pérez Cardozo", departamento: "Guairá" },
  { ciudad: "General Eugenio Alejandrino Garay", departamento: "Guairá" },
  { ciudad: "Independencia", departamento: "Guairá" },
  { ciudad: "Itapé", departamento: "Guairá" },
  { ciudad: "Iturbe", departamento: "Guairá" },
  { ciudad: "José A. Fassardi", departamento: "Guairá" },
  { ciudad: "Mbocayaty del Guairá", departamento: "Guairá" },
  { ciudad: "Natalicio Talavera", departamento: "Guairá" },
  { ciudad: "Ñumí", departamento: "Guairá" },
  { ciudad: "Paso Yobái", departamento: "Guairá" },
  { ciudad: "San Salvador", departamento: "Guairá" },
  { ciudad: "Tebicuary", departamento: "Guairá" },
  { ciudad: "Villarrica", departamento: "Guairá" },
  { ciudad: "Yataity del Guairá", departamento: "Guairá" },
  { ciudad: "Alto Verá", departamento: "Itapúa" },
  { ciudad: "Bella Vista", departamento: "Itapúa" },
  { ciudad: "Cambyretá", departamento: "Itapúa" },
  { ciudad: "Capitán Meza", departamento: "Itapúa" },
  { ciudad: "Capitán Miranda", departamento: "Itapúa" },
  { ciudad: "Carlos Antonio López", departamento: "Itapúa" },
  { ciudad: "Carmen del Paraná", departamento: "Itapúa" },
  { ciudad: "Coronel José Félix Bogado", departamento: "Itapúa" },
  { ciudad: "Edelira", departamento: "Itapúa" },
  { ciudad: "Encarnación", departamento: "Itapúa" },
  { ciudad: "Fram", departamento: "Itapúa" },
  { ciudad: "General Artigas", departamento: "Itapúa" },
  { ciudad: "General Delgado", departamento: "Itapúa" },
  { ciudad: "Hohenau", departamento: "Itapúa" },
  { ciudad: "Itapúa Poty", departamento: "Itapúa" },
  { ciudad: "Jesús de Tavarangüé", departamento: "Itapúa" },
  { ciudad: "José Leandro Oviedo", departamento: "Itapúa" },
  { ciudad: "La Paz", departamento: "Itapúa" },
  { ciudad: "Mayor Julio Dionisio Otaño", departamento: "Itapúa" },
  { ciudad: "Natalio", departamento: "Itapúa" },
  { ciudad: "Nueva Alborada", departamento: "Itapúa" },
  { ciudad: "Obligado", departamento: "Itapúa" },
  { ciudad: "Pirapó", departamento: "Itapúa" },
  { ciudad: "San Cosme y Damián", departamento: "Itapúa" },
  { ciudad: "San Juan del Paraná", departamento: "Itapúa" },
  { ciudad: "San Pedro del Paraná", departamento: "Itapúa" },
  { ciudad: "San Rafael del Paraná", departamento: "Itapúa" },
  { ciudad: "Tomás Romero Pereira", departamento: "Itapúa" },
  { ciudad: "Trinidad", departamento: "Itapúa" },
  { ciudad: "Yatytay", departamento: "Itapúa" },
  { ciudad: "Ayolas", departamento: "Misiones" },
  { ciudad: "San Ignacio Guazú", departamento: "Misiones" },
  { ciudad: "San Juan Bautista", departamento: "Misiones" },
  { ciudad: "San Miguel", departamento: "Misiones" },
  { ciudad: "San Patricio", departamento: "Misiones" },
  { ciudad: "Santa María de Fe", departamento: "Misiones" },
  { ciudad: "Santa Rosa de Lima", departamento: "Misiones" },
  { ciudad: "Santiago", departamento: "Misiones" },
  { ciudad: "Villa Florida", departamento: "Misiones" },
  { ciudad: "Yabebyry", departamento: "Misiones" },
  { ciudad: "Alberdi", departamento: "Ñeembucú" },
  { ciudad: "Cerrito", departamento: "Ñeembucú" },
  { ciudad: "Desmochados", departamento: "Ñeembucú" },
  { ciudad: "General José Eduvigis Díaz", departamento: "Ñeembucú" },
  { ciudad: "Guazú Cuá", departamento: "Ñeembucú" },
  { ciudad: "Humaitá", departamento: "Ñeembucú" },
  { ciudad: "Isla Umbú", departamento: "Ñeembucú" },
  { ciudad: "Laureles", departamento: "Ñeembucú" },
  { ciudad: "Mayor José Martínez", departamento: "Ñeembucú" },
  { ciudad: "Paso de Patria", departamento: "Ñeembucú" },
  { ciudad: "Pilar", departamento: "Ñeembucú" },
  { ciudad: "San Juan Bautista de Ñeembucú", departamento: "Ñeembucú" },
  { ciudad: "Tacuaras", departamento: "Ñeembucú" },
  { ciudad: "Villa Franca", departamento: "Ñeembucú" },
  { ciudad: "Villa Oliva", departamento: "Ñeembucú" },
  { ciudad: "Villalbín", departamento: "Ñeembucú" },
  { ciudad: "Acahay", departamento: "Paraguarí" },
  { ciudad: "Caapucú", departamento: "Paraguarí" },
  { ciudad: "Carapeguá", departamento: "Paraguarí" },
  { ciudad: "Escobar", departamento: "Paraguarí" },
  { ciudad: "General Bernardino Caballero", departamento: "Paraguarí" },
  { ciudad: "La Colmena", departamento: "Paraguarí" },
  { ciudad: "María Antonia", departamento: "Paraguarí" },
  { ciudad: "Mbuyapey", departamento: "Paraguarí" },
  { ciudad: "Paraguarí", departamento: "Paraguarí" },
  { ciudad: "Pirayú", departamento: "Paraguarí" },
  { ciudad: "Quiindy", departamento: "Paraguarí" },
  { ciudad: "Quyquyhó", departamento: "Paraguarí" },
  { ciudad: "San Roque González de Santa Cruz", departamento: "Paraguarí" },
  { ciudad: "Sapucai", departamento: "Paraguarí" },
  { ciudad: "Tebicuarymí", departamento: "Paraguarí" },
  { ciudad: "Yaguarón", departamento: "Paraguarí" },
  { ciudad: "Ybycuí", departamento: "Paraguarí" },
  { ciudad: "Ybytymí", departamento: "Paraguarí" },
  { ciudad: "Benjamín Aceval", departamento: "Presidente Hayes" },
  { ciudad: "Campo Aceval", departamento: "Presidente Hayes" },
  { ciudad: "General José María Bruguez", departamento: "Presidente Hayes" },
  { ciudad: "José Falcón", departamento: "Presidente Hayes" },
  { ciudad: "Nanawa", departamento: "Presidente Hayes" },
  { ciudad: "Nueva Asunción", departamento: "Presidente Hayes" },
  { ciudad: "Puerto Pinasco", departamento: "Presidente Hayes" },
  { ciudad: "Teniente Esteban Martínez", departamento: "Presidente Hayes" },
  { ciudad: "Teniente Primero Manuel Irala Fernández", departamento: "Presidente Hayes" },
  { ciudad: "Villa Hayes", departamento: "Presidente Hayes" },
  { ciudad: "Antequera", departamento: "San Pedro" },
  { ciudad: "Capiibary", departamento: "San Pedro" },
  { ciudad: "Choré", departamento: "San Pedro" },
  { ciudad: "General Elizardo Aquino", departamento: "San Pedro" },
  { ciudad: "General Isidoro Resquín", departamento: "San Pedro" },
  { ciudad: "Guayaibí", departamento: "San Pedro" },
  { ciudad: "Itacurubí del Rosario", departamento: "San Pedro" },
  { ciudad: "Liberación", departamento: "San Pedro" },
  { ciudad: "Lima", departamento: "San Pedro" },
  { ciudad: "Nueva Germania", departamento: "San Pedro" },
  { ciudad: "San José del Rosario", departamento: "San Pedro" },
  { ciudad: "San Estanislao", departamento: "San Pedro" },
  { ciudad: "San Pablo", departamento: "San Pedro" },
  { ciudad: "San Pedro de Ycuamandiyú", departamento: "San Pedro" },
  { ciudad: "San Vicente Pancholo", departamento: "San Pedro" },
  { ciudad: "Santa Rosa del Aguaray", departamento: "San Pedro" },
  { ciudad: "Tacuatí", departamento: "San Pedro" },
  { ciudad: "Unión", departamento: "San Pedro" },
  { ciudad: "Veinticinco de Diciembre", departamento: "San Pedro" },
  { ciudad: "Villa del Rosario", departamento: "San Pedro" },
  { ciudad: "Yataity del Norte", departamento: "San Pedro" },
  { ciudad: "Yrybucuá", departamento: "San Pedro" },
]

// Filas bilingües del catálogo (misma identidad, dos idiomas de claves).
export const CIUDADES_PARAGUAY = MUNICIPIOS.map(({ ciudad, departamento }) => ({
  ciudad,
  departamento,
  city: ciudad,
  department: departamento,
}))

export const DEPARTAMENTOS_PARAGUAY = [
  "Alto Paraguay",
  "Alto Paraná",
  "Amambay",
  "Asunción",
  "Boquerón",
  "Caaguazú",
  "Caazapá",
  "Canindeyú",
  "Central",
  "Concepción",
  "Cordillera",
  "Guairá",
  "Itapúa",
  "Misiones",
  "Ñeembucú",
  "Paraguarí",
  "Presidente Hayes",
  "San Pedro",
]

const norm = (valor) => String(valor || "").normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase().trim()

// Departamento de una ciudad por nombre exacto (sin acentos ni mayúsculas).
export function departamentoDe(ciudad) {
  const buscado = norm(ciudad)
  if (!buscado) return ""
  const fila = CIUDADES_PARAGUAY.find((item) => norm(item.ciudad) === buscado)
  return fila?.departamento || ""
}

// Busca por ciudad o departamento, con las coincidencias al principio primero.
// Devuelve las filas bilingües (`ciudad`/`departamento` y `city`/`department`).
export function buscarCiudad(texto, limite = 8) {
  const q = norm(texto)
  if (q.length < 2) return []
  return CIUDADES_PARAGUAY
    .filter(({ ciudad, departamento }) => norm(ciudad).includes(q) || norm(departamento).includes(q))
    .sort((a, b) => {
      const aInicio = norm(a.ciudad).startsWith(q) ? 0 : 1
      const bInicio = norm(b.ciudad).startsWith(q) ? 0 : 1
      return aInicio - bInicio || a.ciudad.localeCompare(b.ciudad, "es")
    })
    .slice(0, limite)
    .map(({ ciudad, departamento, city, department }) => ({ ciudad, departamento, city, department }))
}
